openapi: 3.0.0
info:
  title: 1-Time Secret API
  version: 1.0.0
  description: API gửi nội dung bí mật chỉ đọc một lần
servers:
  - url: 'http://localhost:3000/api'
paths:
  /secret:
    post:
      summary: Tạo một secret mới
      tags:
        - Secret
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecretCreate'
      responses:
        '201':
          description: Secret được tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretCreated'
        '400':
          description: Thiếu nội dung
  '/secret/{id}':
    post:
      summary: Lay một secret
      tags:
        - Secret
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecretCreate'
      responses:
        '201':
          description: Secret được tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretCreated'
        '400':
          description: Thiếu nội dung
components:
  schemas:
    SecretCreate:
      type: object
      properties:
        content:
          type: string
          example: Đây là nội dung bí mật
        password:
          type: string
          example: 123456
      required:
        - content
    SecretCreated:
      type: object
      properties:
        message:
          type: string
          example: Secret created
        accessUrl:
          type: string
          example: 'http://localhost:3000/api/secret/abc123xyz'
    SecretReadPassword:
      type: object
      properties:
        password:
          type: string
          example: 123456
    SecretContent:
      type: object
      properties:
        content:
          type: string
          example: Đây là nội dung bí mật
